name: Update quotes (cron)
run-name: Update quotes (cron) #${{ github.run_number }}
on:
  schedule:
    # Run only during regular US market hours (approx, UTC):
    # 13:30–13:59, then 14:00–19:59, then 20:00–20:10, Mon–Fri
    - cron: "30-59/10 13 * * 1-5"
    - cron: "*/10 14-19 * * 1-5"
    - cron: "0-10/10 20 * * 1-5"
    # Shanghai regular hours (UTC): 01:30–03:30 and 05:00–07:00 Mon–Fri
    - cron: "30-59/10 1 * * 1-5"
    - cron: "*/10 2-3 * * 1-5"
    - cron: "*/10 5-6 * * 1-5"
    - cron: "0 7 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests==2.32.3
      - name: Generate quotes.json
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
          TWELVEDATA_TOKEN: ${{ secrets.TWELVEDATA_TOKEN }}
        run: |
          python scripts/quotes.py
          test -f data/quotes.json && head -n 40 data/quotes.json || true
          test -f public/quotes.json && head -n 40 public/quotes.json || true
      - name: Build companies index
        run: |
          python scripts/build_companies_index.py
          test -f public/companies/index.json && head -n 40 public/companies/index.json || true
      - name: Run summary (UTC/NY time)
        run: |
          echo "### Quotes run #${GITHUB_RUN_NUMBER}" >> $GITHUB_STEP_SUMMARY
          echo "UTC: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_STEP_SUMMARY
          echo "New York: $(TZ=America/New_York date +"%Y-%m-%d %H:%M:%S %Z")" >> $GITHUB_STEP_SUMMARY
      - name: Commit quotes/index if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/quotes.json public/quotes.json public/companies || true
          git commit -m "data(quotes): refresh quotes & companies index" || echo "no changes"
          git push
