name: Update quotes (cron)
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests==2.32.3 yfinance==0.2.52 pandas==2.2.2 numpy==1.26.4
      - name: Generate quotes.json
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
        run: |
          python scripts/quotes.py
          test -f data/quotes.json && head -n 40 data/quotes.json || true
      - name: Commit quotes.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/quotes.json
          git commit -m "data(quotes): refresh quotes.json" || echo "no changes"
          git push
